I'm sorry, but an uncaught exception occurred.

While running game code:
  File "game/battle.rpy", line 281, in script
    return _return
  File "game/battle.rpy", line 281, in script
    return _return
ScriptError: could not find label '(u'C:\\Users\\Matt\\Documents\\GitHub\\BattleSystem\\Battle/game/script.rpy', 1401337499, 5)'.

-- Full Traceback ------------------------------------------------------------

Full traceback:
  File "game/battle.rpy", line 281, in script
    return _return
  File "C:\Users\Matt\Desktop\renpy-6.16.5-sdk\renpy\ast.py", line 1286, in execute
    next_node(renpy.game.context().lookup_return(pop=True))
  File "game/battle.rpy", line 281, in script
    return _return
  File "C:\Users\Matt\Desktop\renpy-6.16.5-sdk\renpy\script.py", line 549, in lookup
    raise ScriptError("could not find label '%s'." % str(label))
ScriptError: could not find label '(u'C:\\Users\\Matt\\Documents\\GitHub\\BattleSystem\\Battle/game/script.rpy', 1401337499, 5)'.

Windows-7-6.1.7601-SP1
Ren'Py 6.17.7.521
House Guard 0.0
