I'm sorry, but an uncaught exception occurred.

Executing ATL code at game/battle.rpy:6
  File "game/script.rpy", line 87, in script call
    call battle()
  File "game/battle.rpy", line 80, in script
    show boss at shake(100)
Exception: ATL appears to be in an infinite loop.

-- Full Traceback ------------------------------------------------------------

Full traceback:
  File "game/script.rpy", line 87, in script call
    call battle()
  File "game/battle.rpy", line 80, in script
    show boss at shake(100)
  File "C:\Users\Cory\Desktop\renpy-6.17.6-sdk\renpy\ast.py", line 1003, in execute
    show_imspec(self.imspec, atl=getattr(self, "atl", None))
  File "C:\Users\Cory\Desktop\renpy-6.17.6-sdk\renpy\ast.py", line 976, in show_imspec
    atl=atl)
  File "C:\Users\Cory\Desktop\renpy-6.17.6-sdk\renpy\exports.py", line 443, in show
    sls.add(layer, img, key, zorder, behind, at_list=at_list, name=name, atl=atl, default_transform=renpy.config.default_transform, transient=transient)
  File "C:\Users\Cory\Desktop\renpy-6.17.6-sdk\renpy\display\core.py", line 759, in add
    thing._show()
  File "C:\Users\Cory\Desktop\renpy-6.17.6-sdk\renpy\display\motion.py", line 858, in _show
    super(ATLTransform, self)._show()
  File "C:\Users\Cory\Desktop\renpy-6.17.6-sdk\renpy\display\motion.py", line 845, in _show
    self.update_state()
  File "C:\Users\Cory\Desktop\renpy-6.17.6-sdk\renpy\display\motion.py", line 706, in update_state
    fr = self.function(self, self.st, self.at)
  File "C:\Users\Cory\Desktop\renpy-6.17.6-sdk\renpy\atl.py", line 394, in execute
    action, arg, pause = self.block.execute(trans, timebase, self.atl_state, event)
  File "C:\Users\Cory\Desktop\renpy-6.17.6-sdk\renpy\atl.py", line 587, in execute
    raise Exception("ATL appears to be in an infinite loop.")
Exception: ATL appears to be in an infinite loop.

Windows-7-6.1.7601-SP1
Ren'Py 6.17.6.512
House Guard 0.0
